[defaults]
setup = ["cosmos"]
timeout = 10

[chain_types.ethereum]
timeout = 20

[binary.cosmos_ethereum]
setup = ["cosmos", "ethereum"]

[chain_types.solana]
timeout = 15

[binary.cosmos_solana]
setup = ["cosmos", "solana"]

[test_overrides.beacon]
pattern = "_beacon"
extra_setup = ["kurtosis"]
timeout = 25
